services:
  rest:
    image: rest:1.0.0
    build:
      context: ../..
      dockerfile: ./examples/rest/Dockerfile
    environment:
      - PORT=8080
    restart: unless-stopped
    ports:
      - 8080:8080
