[env]
TARGET = "server"
DEV_MODE = true
HOST = "0.0.0.0"
PORT = 8080

[tasks.dev]
description = "Run application in dev mode"
run = [{ tasks = ["watch-app"] }]

# -----------------------------------------------------------------------------
# API
# -----------------------------------------------------------------------------

[tasks.build]
description = "Build and run dashboard"
depends = ["app-install"]
quiet = true
hide = true
run = "cmake --build build -j$(nproc) --target $TARGET"

[tasks.app-run]
description = "Build and run dashboard"
depends = ["build"]
quiet = true
hide = true
run = "cd ./build/examples/$TARGET && ./$TARGET"

[tasks.watch-app]
description = "Watch and run application"
quiet = true
run = "mise w -r -w src -w examples app-run"

[tasks.app-install]
description = "Build and run application"
quiet = true
hide = true
run = "cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON"

[tasks.test]
description = "Run tests"
env = {
    POLL_TIMEOUT = 300,
}
quiet = true
run = "cmake -S . -B build -DBUILD_TESTS:BOOL=ON && cmake --build build -j$(nproc) && ./build/test/tests"

# -----------------------------------------------------------------------------
# Miscellaneous
# -----------------------------------------------------------------------------

[tasks.clean]
description = "Cleanup"
quiet = true
run = "rm -rf ./build ./web/node_modules assets/ui .cache"

[tasks.prod-up]
description = 'Bring up production environment'
quiet = true
run = '''
docker compose -f docker/compose.yml up -d --build
docker image prune -a -f
'''

[tasks.prod-down]
description = 'Take down production environment'
quiet = true
run = 'docker compose -f docker/compose.yml down'
