[env]
DEV_MODE = true
HOST = "0.0.0.0"
PORT = 8080

[tasks.dev]
description = "Run application in dev mode"
quiet = true
usage = '''
arg "<example>" default="server"
'''
run = [
  'mise w -r -w src -w examples app-run ${usage_example?}',
]
# run = [{ tasks = ["watch-app"] }]

# -----------------------------------------------------------------------------
# API
# -----------------------------------------------------------------------------

[tasks.build]
description = "Build and run dashboard"
depends = ["app-install"]
usage = 'arg "<example>" default="server"'
quiet = true
hide = true
run = "cmake --build build -j$(nproc) --target {{usage.example}}"

[tasks.app-run]
description = "Build and run dashboard"
usage = 'arg "<example>"'
depends = [{task = "build", args = ["{{usage.example}}"]}]
quiet = true
hide = true
run = "cd ./build/examples/{{usage.example}} && ./{{usage.example}} || true"

[tasks.app-install]
description = "Build and run application"
quiet = true
hide = true
run = "cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON"

[tasks.test]
description = "Run tests"
env = {
    POLL_TIMEOUT = 300,
}
quiet = true
run = "cmake -S . -B build -DBUILD_TESTS:BOOL=ON && cmake --build build -j$(nproc) && ./build/test/tests"

# -----------------------------------------------------------------------------
# Miscellaneous
# -----------------------------------------------------------------------------

[tasks.clean]
description = "Cleanup"
quiet = true
run = "rm -rf ./build ./web/node_modules assets/ui .cache"

[tasks.docker-up]
description = 'Bring up production environment'
quiet = true
run = '''
docker compose -f examples/docker/compose.yml up -d --build
docker image prune -a -f
'''

[tasks.docker-down]
description = 'Take down production environment'
quiet = true
run = 'docker compose -f examples/docker/compose.yml down'
